// AUTH
export const INIT_AUTH_PATH = 'INIT_AUTH_PATH';
export const INITIAL_REGISTER_USER = 'INITIAL_REGISTER_USER';
export const SUCESS_REGISTER_USER = 'SUCESS_REGISTER_USER';
export const INITIAL_LOGIN_USER = 'INITIAL_LOGIN_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// PROFILE
export const INITIAL_GET_PROFILE = 'INITIAL_GET_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const INITIAL_GET_PROFILES = 'INITIAL_GET_PROFILES';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILE_BY_HANDLE = 'GET_PROFILE_BY_HANDLE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const INITIAL_CREATE_PROFILE = 'INITIAL_CREATE_PROFILE';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
