// AUTH
export const INIT_AUTH_PATH = 'INIT_AUTH_PATH';
export const INITIAL_REGISTER_USER = 'INITIAL_REGISTER_USER';
export const SUCESS_REGISTER_USER = 'SUCESS_REGISTER_USER';
export const INITIAL_LOGIN_USER = 'INITIAL_LOGIN_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const GET_ERRORS = 'GET_ERRORS';
